name: flutter_chat_demo
description: This is the demo for chat app by Flutter
publish_to: 'none'

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.9
  fluttertoast: ^8.2.12
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  firebase_storage: ^12.4.7
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.2.1
  photo_view: ^0.15.0
  provider: ^6.1.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - images/

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.32.1"